### ISSUE TITLE
App compiles even with typescript error?

### ISSUE THREAD

**Issue by kjmj** [vuejs/eslint-config-typescript#20]
Assume I have this code:
```
function foo(bar: string) {
  console.log(bar)
}
foo(3);
```

When I run `yarn serve`, an type error is thrown to the console: 
```
10:3 Argument of type 'number' is not assignable to parameter of type 'string'.
```

However, the project compiles and launches in my web browser. I would expect for the project to fail compilation until all typescript errors are fixed.

Is this expected behavior, or is there an additional config for this?

**Comment by sodatea** [comment]
Expected. Type checking is non-blocking in Vue CLI because it's too slow.

It is configurable in some way, but it's also tedious:
You need to tap into the `fork-ts-checker-webpack-plugin` configurations to disable the `async` option: https://github.com/vuejs/vue-cli/blob/aaa7eb05874ee8edd3d97b95c44779b8055a3c3d/packages/%40vue/cli-plugin-typescript/index.js#L81-L84 https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#options
