### ISSUE TITLE
Wrongly installed @typescript-eslint/eslint-plugin

### ISSUE THREAD

**Issue by fdc-viktor-luft** [vuejs/eslint-config-typescript#59]
The dependency `@typescript-eslint/eslint-plugin` is wrongly installed as it causes another plugin version to be used or even fails to resolve the plugin in a `pnpm` workspace.

This could be easily solved by declaring these as `peerDependencies` instead of `dependencies`.

My current workaround: Install `@typescript-eslint/eslint-plugin` manually and keep versions in sync with the one listed in `@vue/eslint-config-typescript`.

**Comment by fdc-viktor-luft** [comment]
Of course this dependency should also be moved `@typescript-eslint/parser` as it should be always identical to the above one.

**Comment by fdc-viktor-luft** [comment]
@sodatea Why did you not consider my issue correctly? 😩

The newly released version v12 now has a similar issue.

My VSCode plugin (official ESLint plugin) stops working if the dependency `"@typescript-eslint/eslint-plugin": "6.7.0"` is not installed in the workspace in addition to the `"@vue/eslint-config-typescript": "12.0.0"` dependency.

Since you released a new major version, I guess no one would've complained making it a peer dependency instead.

**Comment by sodatea** [comment]
This issue was closed because the linked PR claimed it had fixed this one, sorry if that's not related.

On making `typescript-eslint` peer dependencies:
- In the README of this project, we explicitly recommend using this package with `@rushstack/eslint-patch` https://github.com/vuejs/eslint-config-typescript#vueeslint-config-typescript-1 Your config in https://github.com/typescript-eslint/typescript-eslint/issues/7211 doesn't seem to have that included.
- I currently do not intend to make the plugin and parser peer dependencies, because that's a maintenance nightmare. I would like to switch to [ESLint Flat Config](https://eslint.org/docs/latest/use/configure/configuration-files-new) when possible, though.

**Comment by fdc-viktor-luft** [comment]
@sodatea Thank you a lot for the explanation. That helps me :+1:
