### ISSUE TITLE
Support additional typescript-eslint configs

### ISSUE THREAD

**Issue by rijenkii** [vuejs/eslint-config-typescript#73]
https://typescript-eslint.io/users/configs#recommended-configurations:
- `recommended-type-checked(-only)`
- `strict(-type-checked(-only))`
- `stylistic(-type-checked(-only))`
- `all`
- `base`
- `disable-type-checked`

Currently it seems that only `eslint-recommended` and `recommended` are provided.

**Comment by bmulholland** [comment]
@haoqunjiang This was closed by #81, but that PR notes "I'm afraid I can't get the *-type-checked configurations right on the first try; I'm not sure about the performance in large projects either"

I spent a while trying to get this working and was confused by the error I got: `Cannot read properties of undefined (reading 'files')`

I guess this didn't actually make it in, and should be re-opened?

**Comment by bmulholland** [comment]
Ah but this is a dupe of the older https://github.com/vuejs/eslint-config-typescript/issues/67, right?

**Comment by haoqunjiang** [comment]
> I spent a while trying to get this working and was confused by the error I got: `Cannot read properties of undefined (reading 'files')`

You might have accidentally used the kebab-case names instead of camelCase.
It was an unfortunate oversight when I implemented this feature, but I can't change that now due to semver constraints, and supporting both cases would mess up the TypeScript suggestions.
In v14.1.2 I added more friendly error messages for such errors. Could you try it out?

**Comment by bmulholland** [comment]
@haoqunjiang Ah nice. Yes, that was it -- and the error message would have saved me time. Cool, all good then.  Thank you!
